server:
  port: 8080

storage: 
  location: /Users/hamidporasl/storage
spring:
 data:
  mongodb:
      uri: mongodb://localhost:27017/contents

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
logging:
  level:
   org:
    springframework:
     beans:
      factory: DEBUG
